name: Linting & Unit Test

on:
  push:
    branches: [OCRVS-2106]
  pull_request:
    branches: [OCRVS-2106]

  workflow_dispatch:

jobs:
  test:
    name: Unit Test & Linting & Code Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Runs dependency installation
        run: |
          npm install yarn lerna
          yarn

      - name: Run linting & unit testing
        run: yarn test && yarn lint

      - name: Run code coverage
        if: ${{ success() }}
        run: |
          npm install codecov
          ./node_modules/.bin/codecov
          # ./node_modules/.bin/bundlesize

  E2E:
    name: Integration Test
    runs-on: ubuntu-latest
    # needs: [test]
    env:
      CYPRESS_LOGIN_URL: http://localhost:3020/
      CYPRESS_CLIENT_URL: http://localhost:3000/
      CYPRESS_AUTH_URL: http://localhost:4040/
    steps:
      - uses: actions/checkout@v2

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3

      - name: Execute integration test
        run: |
          while sleep 9m; do echo "=====[ $SECONDS seconds still running ]====="; done &
          ./infrastructure/build-and-test-e2e-on-staging.sh
          kill %1
  # slackNotification:
  #   name: Slack Notification
  #   runs-on: ubuntu-latest
  #   # needs: [test]
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: 8398a7/action-slack@v3
  #       with:
  #         status: ${{ job.status }}
  #         fields: repo,message,commit,author,action,eventName,ref,workflow,job,took # selectable (default: repo,message)
  #       env:
  #         SLACK_WEBHOOK_URL: https://hooks.slack.com/services/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
