# This is a basic workflow to help you get started with Actions

name: Linting & Unit Test

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [OCRVS-2106]
  pull_request:
    branches: [OCRVS-2106]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      CYPRESS_LOGIN_URL: http://localhost:3020/
      CYPRESS_CLIENT_URL: http://localhost:3000/
      CYPRESS_AUTH_URL: http://localhost:4040/

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs dependency installation
      - name: Runs dependency installation
        run: |
          npm install yarn lerna
          yarn      

      # Runs a single command using the runners shell
      - name: Run linting & unit testing
        run: yarn test && yarn lint

      - name: Run code coverage
        if: ${{ success() }}
        run: |
          npm install codecov
          ./node_modules/.bin/codecov
          # ./node_modules/.bin/bundlesize
  # slackNotification:
  #   name: Slack Notification
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Slack Notification
  #     uses: rtCamp/action-slack-notify@v2
  #     env:
  #       SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
