name: Linting & Unit Test

on: [push, pull_request]

jobs:
  test:
    name: Unit Test & Linting & Code Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Runs dependency installation
        run: |
          npm install yarn lerna
          yarn

      - name: Run linting & unit testing
        run: yarn test && yarn lint

      - name: Run code coverage
        if: ${{ success() }}
        run: |
          npm install codecov
          ./node_modules/.bin/codecov
          # ./node_modules/.bin/bundlesize  

  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    needs: test
    # if: ${{ needs.test.result == 'failure' }}
    if: ${{ always() }}
    steps:
      - name: Using Slack Action to Send message
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
